# Add this to your .pre-commit.yaml to use this hook:
  - id: check-todos
    files: '**/*'  # Adjust pattern to match files you want to check
    enabled: true
    command: /Users/Nat/Work/precommit-rs/check-todos/check-todos.py